### ISSUE TITLE
function graphile_worker.add_job(unknown, unknown) is not unique

### ISSUE THREAD

**Issue by ffissore** [graphile/worker#94] opened 2020-03-05 14:26 UTC
Our app uses graphile worker as a library and sets it up at startup time. When running e2e tests, we start multiple instances of our app and sometimes we get the error

`function graphile_worker.add_job(unknown, unknown) is not unique`

I think this is related to unlucky timing of migrations run by graphile. This might be fixed by running migrations in a transaction and running a `SELECT pg_advisory_xact_lock(SHARED_LOCK_KEY_HERE);`. It's important that the value stays the same across different builds/instances/etc: hard coding it works just fine

**Comment by benjie** [comment] 2020-03-11 13:45
Each of the graphile-worker migrations are ran in a transaction:

https://github.com/graphile/worker/blob/658c93a1ce55d45fab785ff1fb01e7565bcb92b1/src/migrate.ts#L30-L47

so the changes they make are atomic. The relevant parts of the migrations are below; as far as I can tell at every point the signatures match the previous add_job signature, so at no point will there ever be two `add_job` functions.

I don't understand why you're seeing this issue... Are you also creating `add_job` using your own code perhaps, e.g. from a `pg_dump` that you've imported?

---

000001:
```sql
...
create function :GRAPHILE_WORKER_SCHEMA.add_job(
  identifier text,
  payload json = '{}',
  queue_name text = public.gen_random_uuid()::text,
  run_at timestamptz = now(),
  max_attempts int = 25
) ...
```

000002:

```sql
...
drop function if exists :GRAPHILE_WORKER_SCHEMA.add_job(
  identifier text,
  payload json,
  queue_name text,
  run_at timestamptz,
  max_attempts int
);
create function :GRAPHILE_WORKER_SCHEMA.add_job(
  identifier text,
  payload json = '{}',
  queue_name text = null,
  run_at timestamptz = now(),
  max_attempts int = 25,
  job_key text = null
) ...
```

000003:

```sql
...
create or replace function :GRAPHILE_WORKER_SCHEMA.add_job(
  identifier text,
  payload json = '{}',
  queue_name text = null,
  run_at timestamptz = now(),
  max_attempts int = 25,
  job_key text = null
) ...
```

000004:

```sql
...
drop function :GRAPHILE_WORKER_SCHEMA.add_job(text, json, text, timestamptz, int, text);

create function :GRAPHILE_WORKER_SCHEMA.add_job(
  identifier text,
  payload json = null,
  queue_name text = null,
  run_at timestamptz = null,
  max_attempts int = null,
  job_key text = null,
  priority int = null
) ...
```

---

I'm going to close this because I'm fairly certain this is not a bug in graphile-worker.

**Closed by benjie** 2020-03-11 13:45 UTC
