### ISSUE TITLE
Handle SIGINT gracefully.

### ISSUE THREAD

**Issue by jjcroftiv** [graphile/worker#29] opened 2019-09-27 18:09 UTC
I have added graphile-worker to my project and have it running.  When I kill the node app, I get the following message:

```^CReceived 'SIGINT'; attempting graceful shutdown...
/var/local/fileserver/vcs/git/laminar-pgphile/laminar-pgphile/node_modules/graphile-worker/dist/main.js:37
            Promise.all(allWorkerPools.map(pool => pool.gracefulShutdown(`Forced worker shutdown due to ${signal}`))).finally(() => {
                                                                                                                             ^

TypeError: Promise.all(...).finally is not a function
    at process.handler (/var/local/fileserver/vcs/git/laminar-pgphile/laminar-pgphile/node_modules/graphile-worker/dist/main.js:37:126)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at Signal.wrap.onsignal (internal/process.js:197:44)
```

Does a finally block need to be added to the Promise.all running the workers, or do I need to pass something in to avoid this message?

**Comment by benjie** [comment] 2019-09-27 20:22
What version of node are you running?

**Comment by jjcroftiv** [comment] 2019-09-27 20:33
8.16.1

**Comment by benjie** [comment] 2019-09-27 23:09
You need Node 10.3+ for Promise.finally to work.

We officially require Node 10, so I’m going to close this as not a bug 👍

https://github.com/graphile/worker#requirements

**Closed by benjie** 2019-09-27 23:09 UTC

**Comment by jjcroftiv** [comment] 2019-09-30 18:09
Thank you, I will get the project up to the latest node version.
