### ISSUE TITLE
Tests require database to be at localhost:5432

### ISSUE THREAD

**Issue by jcgsville** [graphile/worker#518] opened 2024-12-05 01:13 UTC
### Description

Connection strings in the tests are currently hardcoded to use `postgres:///${db}`. This requires that the Postgres db is available at `localhost:5432`. I'd like to update the tests so that they respect `DATABASE_URL` and `PG*` environment variables like the main library does.

### Motivating example

This improvement would enable using remote Postgres databases like neon.tech for development. It would also allow tests to be run successfully in docker compose.

### Breaking changes

I think this will only impact testing, though I need to dig into the implementation more to verify this.

### Supporting development

I:

- [x] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [x] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- ⛔️ have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment] 2024-12-05 07:49
DATABASE_URL won’t work with the tests because each spins up its own fresh database (and thus uses a different DBURL). Are you sure PGHOST and PGPORT don’t already work? Since we use `postgres:///` it should use the defaults for host/port/user/pass all of which can come from envvars I think?

**Comment by benjie** [comment] 2024-12-05 10:05
I've confirmed that we don't require the Postgres instance to be at localhost:5432

1. Shut down postgres
2. Run tests (fail: no DB)
3. Run Postgres via docker on a custom port: `docker run --rm -it -e POSTGRES_USER=benjie -e POSTGRES_HOST_AUTH_METHOD=trust -p 6432:5432 postgres:17 -c wal_level=logical`
4. Run tests using custom envvars: `PGPORT=6432 PGHOST=127.0.0.1 yarn test`

Tests pass :+1:

**Comment by benjie** [comment] 2024-12-05 10:06
You may want to reference the changes to contributing that we made for the crystal repo:

https://github.com/graphile/crystal/pull/2260/files

**Comment by benjie** [comment] 2024-12-05 11:01
Fixed in #517

**Closed by benjie** 2024-12-05 11:01 UTC

**Comment by jcgsville** [comment] 2024-12-05 15:49
Huh. Apologies for the false alarm. I could've sworn I tried it with the PG* environment variables, but I must have mixed something up as I was getting my bearings. I'm glad it's documented now for future people 🙂
