### ISSUE TITLE
ENOTFOUND Error

### ISSUE THREAD

**Issue by fred-zummo** [graphile/worker#346] opened 2023-09-28 17:52 UTC
### Summary

Fix a bug in graphile-worker library whereby graphile-worker loses its connection to the database and cannot reconnect.

### Steps to reproduce

1. Graphile worker starts up.
2. A database connection is established.
3. Database server goes down, or is rebooted for whatever reason.
4. Graphile worker loses its connection to the database.
5. ENOTFOUND errors start appearing.
6. Database server is back online again.
7. Graphile worker never reestablishes its connection to the database.
8. ENOTFOUND errors continue.

### Expected results

Expect graphile-worker to automatically recover from brief database server outages.

### Actual results

Graphile worker loses its connection to the database, and never recovers.

### Additional context

RHEL7/8.  Node.js v18.x, pm2, postgres DB.

### Possible Solution

Unknown.

Sample error:
[ENOTFOUND_Error.txt](https://github.com/graphile/worker/files/12752450/ENOTFOUND_Error.txt)

**Comment by benjie** [comment] 2023-09-29 10:17
This sounds like a networking issue to me - ENOTFOUND means the domain can't resolve. I strongly suspect that this is an issue with your networking setup rather than with Graphile Worker itself - it continually tries to reconnect to the database (this is expected and desired behavior) but the databases' connection string cannot resolve (this is both undesired AND there's nothing Worker can do about it because it's handled by the operating system).

I'm going to close this because I don't think we can do anything about it - the problem is with your networking stack. If you can prove otherwise, feel free to reopen.

(To confirm: Graphile Worker tollerates database shutdown, downtime, and restart just fine normally.)

**Closed by benjie** 2023-09-29 10:17 UTC
Labels: question
